### ISSUE TITLE
linux sort memory usage excessive

### ISSUE THREAD

**Issue by mkiyer** [yniknafs/taco#19]
decrease memory usage of linux sort and ensure temporary file directory a subdirectory of the taco working directory to avoid file system issues

**Comment by balajipandian** [comment]
I can take a look at this -- It's also not cross-platform parallelized which I'll fix

**Comment by mkiyer** [comment]
linux sort default is to use 1/8th of available RAM, so this was a red herring because we were testing on a system with 128gb ram
